package SensorMeasurementsApplication.Presenters.SensorsMeasurements;

import SensorMeasurementsApplication.Responses.SensorsMeasurements.SensorsMeasurementsResponseModel;

public interface SensorsMeasurementsPresenter {
    SensorsMeasurementsResponseModel prepareSuccessView(SensorsMeasurementsResponseModel response);
}
