package SensorMeasurementsApplication.Presenters.MeteostationsSensors;

import SensorMeasurementsApplication.Exceptions.MeteostationsSensors.MeteostationsSensorsConflictException;
import SensorMeasurementsApplication.Exceptions.MeteostationsSensors.MeteostationsSensorsInvNumbNotFoundException;
import SensorMeasurementsApplication.Exceptions.MeteostationsSensors.MeteostationsSensorsSensorNotFoundException;
import SensorMeasurementsApplication.Exceptions.MeteostationsSensors.MeteostationsSensorsStationNotFoundException;
import SensorMeasurementsApplication.Responses.MeteostationsSensors.Get.MeteostationsSensorsGetResponseModel;
import SensorMeasurementsApplication.Responses.MeteostationsSensors.Post.MeteostationsSensorsPostResponse;

public interface MeteostationsSensorsPresenter {
    MeteostationsSensorsPostResponse prepareSuccessPostView(MeteostationsSensorsPostResponse response);

    MeteostationsSensorsConflictException prepareConflictView();

    MeteostationsSensorsGetResponseModel prepareSuccsessGetView(MeteostationsSensorsGetResponseModel response);

    MeteostationsSensorsInvNumbNotFoundException prepareInventoryNumberNotFoundView();

    MeteostationsSensorsStationNotFoundException prepareStationNotFoundView();

    MeteostationsSensorsSensorNotFoundException prepareSensorNotFoundView();
}
